<?xml version="1.0" encoding="UTF-8"?>

<xs:schema
        targetNamespace="http://pampasim.org/spec/decls"
        xmlns="http://pampasim.org/spec/decls"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        elementFormDefault="qualified">
    <xs:complexType name="processorConfig">
        <xs:attribute name="millionInstructionsPerSecond" default="100" type="xs:positiveInteger"/>
        <xs:attribute name="coreCount" fixed="1" type="xs:positiveInteger"/> <!-- TODO: fixed for now, change when multicore -->
    </xs:complexType>
    <xs:complexType name="entityConfig">
        <xs:sequence>
            <xs:element name="fullyQualifiedClassName" type="xs:string"/>
            <xs:any minOccurs="0"/> <!-- instance configuration -->
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="quantumDeclaration">
        <xs:restriction base="xs:nonNegativeInteger"/>
    </xs:simpleType>

    <xs:element name="quantum" type="quantumDeclaration"/>
</xs:schema>