package org.pampasim.SimCoreRefactor;

public enum EventType {
    PROCESS_ARRIVAL,
    ALLOCATE_PROCESS,
    READY_PROCESS,
    SCHEDULE_PROCESS,
    DISPATCH_PROCESS,
    RUN_PROCESS,
    RUN_PROCESS_ACK,
    RUN_PROCESS_CONTINUE,
    IO_OPERATION,
    PREEMPT_PROCESS,
    PROCESS_EXECUTION_END,
    END_PROCESS,
    KILL_PROCESS
}
