<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://pampasim.org/events/memory"
           xmlns="http://pampasim.org/events/memory" >
    <xs:element name="MMU">
        <xs:complexType>
            <xs:all>
                <xs:element name="swapOperationLength" type="xs:unsignedInt"/>
                <xs:element name="workingSetWindow" type="xs:unsignedInt"/>
                <!-- Name type is a stand-in for a proper java FQCN type -->
                <xs:element name="pageSubstitutionAlgorithm" type="xs:Name"/>
                <xs:element name="globalPageSubstitution" type="xs:boolean"/>
                <xs:element name="anticipatedPageLoading" type="xs:boolean"/>
                <xs:element name="prePagingRange" type="xs:unsignedInt"/>
                <xs:element name="variablePageAllocationThresholds">
                    <xs:simpleType>
                        <xs:list itemType="xs:double"/>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="tlbEnabled" type="xs:boolean" default="false"/>
                <xs:element name="tlbEntries" type="xs:unsignedInt"/>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>
