// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pampaos.proto

// Protobuf Java Version: 3.25.1
package com.pampaos.utils.grpc;

public interface CreateProcessRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateProcessRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 type = 1;</code>
   * @return The type.
   */
  int getType();
}
