// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pampaos.proto

// Protobuf Java Version: 3.25.1
package com.pampaos.utils.grpc;

public final class PampaOsProto {
  private PampaOsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateProcessRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateProcessRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Process_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Process_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProcessList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProcessList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rpampaos.proto\032\033google/protobuf/empty.p" +
      "roto\"$\n\024CreateProcessRequest\022\014\n\004type\030\001 \001" +
      "(\005\"\214\001\n\007Process\022\013\n\003pid\030\001 \001(\005\022\r\n\005state\030\002 \001" +
      "(\005\022\023\n\013arrivalTime\030\003 \001(\005\022\021\n\tburstTime\030\004 \001" +
      "(\005\022\020\n\010priority\030\005 \001(\005\022\024\n\014currExecTime\030\006 \001" +
      "(\005\022\025\n\rexecTimeSlice\030\007 \001(\005\"(\n\013ProcessList" +
      "\022\031\n\007process\030\001 \003(\0132\010.Process2D\n\002Os\022>\n\rCre" +
      "ateProcess\022\025.CreateProcessRequest\032\026.goog" +
      "le.protobuf.Empty2\013\n\tScheduler2\005\n\003Gui2\020\n" +
      "\016VirtualMachineB(\n\026com.pampaos.utils.grp" +
      "cB\014PampaOsProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_CreateProcessRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CreateProcessRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateProcessRequest_descriptor,
        new java.lang.String[] { "Type", });
    internal_static_Process_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Process_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Process_descriptor,
        new java.lang.String[] { "Pid", "State", "ArrivalTime", "BurstTime", "Priority", "CurrExecTime", "ExecTimeSlice", });
    internal_static_ProcessList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ProcessList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProcessList_descriptor,
        new java.lang.String[] { "Process", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
