// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pampaos.proto

// Protobuf Java Version: 3.25.1
package com.pampaos.utils.grpc;

public interface ProcessOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Process)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 pid = 1;</code>
   * @return The pid.
   */
  int getPid();

  /**
   * <code>int32 state = 2;</code>
   * @return The state.
   */
  int getState();

  /**
   * <code>int32 arrivalTime = 3;</code>
   * @return The arrivalTime.
   */
  int getArrivalTime();

  /**
   * <code>int32 burstTime = 4;</code>
   * @return The burstTime.
   */
  int getBurstTime();

  /**
   * <code>int32 priority = 5;</code>
   * @return The priority.
   */
  int getPriority();

  /**
   * <code>int32 currExecTime = 6;</code>
   * @return The currExecTime.
   */
  int getCurrExecTime();

  /**
   * <code>int32 execTimeSlice = 7;</code>
   * @return The execTimeSlice.
   */
  int getExecTimeSlice();
}
