// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pampaos.proto

// Protobuf Java Version: 3.25.1
package com.pampaos.utils.grpc;

public interface ProcessListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProcessList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Process process = 1;</code>
   */
  java.util.List<com.pampaos.utils.grpc.Process> 
      getProcessList();
  /**
   * <code>repeated .Process process = 1;</code>
   */
  com.pampaos.utils.grpc.Process getProcess(int index);
  /**
   * <code>repeated .Process process = 1;</code>
   */
  int getProcessCount();
  /**
   * <code>repeated .Process process = 1;</code>
   */
  java.util.List<? extends com.pampaos.utils.grpc.ProcessOrBuilder> 
      getProcessOrBuilderList();
  /**
   * <code>repeated .Process process = 1;</code>
   */
  com.pampaos.utils.grpc.ProcessOrBuilder getProcessOrBuilder(
      int index);
}
