<?xml version="1.0" encoding="UTF-8"?>

<xs:schema
        targetNamespace="http://pampasim.org/events/process"
        xmlns="http://pampasim.org/events/process"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        elementFormDefault="qualified">
    <xs:element name="processCreationDataPayload">
        <xs:complexType>
            <xs:all>
                <xs:element name="durationTicks" type="xs:positiveInteger"/>
                <xs:element name="startPriority" type="xs:nonNegativeInteger"/>
                <!-- FIXME: regex restriction for the color -->
                <xs:element name="displayColor" type="webColor3"/>
            </xs:all>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="webColor3">
        <xs:restriction base="xs:string">
            <xs:pattern value="([0-9]|[a-f]|[A-F]){6}"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>