package org.pampasim.resources;

import javafx.collections.ObservableList;
import lombok.experimental.StandardException;
import org.pampasim.core.Simulation;
import org.pampasim.resources.viewmodel.ProcessViewModel;

import java.util.Map;

public interface ModuleSimulation extends Simulation {
    /** MUST agree with the behavior of <code>applyConfig(Object config)</code> and <code>saveConfig()</code>
     * @return FQCN for the jakarta XmlRootElement annotated class that encodes this module's configuration.
     */
    Class<?> configClass();

    /** MUST no-op or apply the configuration described by a
     * jakarta XmlRootElement object generated by <code>saveConfig()</code>, in agreement with the behavior of
     * <code>saveConfig()</code> and <code>configClass()</code>
     * @param config spec-provided configuration object
     * @throws ConfigError
     */
    void applyConfig(Object config) throws ConfigError;

    /** MUST return null or a jakarta XmlRootElement annotated
     * object to be serialized on the module entities section of the specification document
     * @return the configuration object instance or null
     */
    Object saveConfig();

    @StandardException
    class ConfigError extends Exception {}
}
