<?xml version="1.0" encoding="UTF-8"?>

<xs:schema
        targetNamespace="http://pampasim.org/"
        xmlns="http://pampasim.org/"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        xmlns:events="http://pampasim.org/events"
        xmlns:process="http://pampasim.org/events/process"
        elementFormDefault="qualified">
    <!-- these comments have semantic value! -->
    <!-- runtime rewrite begin -->
    <xs:import namespace="http://pampasim.org/events" schemaLocation="../../../../../../events/src/main/resources/org/pampasim/events/event.xsd"/>
    <xs:import namespace="http://pampasim.org/events/process" schemaLocation="../../../../../../events/src/main/resources/org/pampasim/events/processCreationData.xsd"/>
    <xs:import namespace="http://pampasim.org/events/memory" schemaLocation="../../../../../../memory/src/main/resources/org/pampasim/resources/memory/memoryProcessCreationData.xsd"/>
    <!-- runtime rewrite end -->

    <xs:element name="spec">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="version">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="major" type="xs:nonNegativeInteger"/>
                            <xs:element name="minor" type="xs:nonNegativeInteger"/>
                            <xs:element name="patch" type="xs:nonNegativeInteger"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="entities">
                    <xs:complexType>
                        <xs:group ref="mandatoryEntities"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="stimuli">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="event" type="events:event" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:group name="mandatoryEntities">
        <xs:all>
            <xs:element name="scheduler" type="schedulerConfig"/>
        </xs:all>
    </xs:group>
    <xs:complexType name="processorConfig">
        <xs:attribute name="millionInstructionsPerSecond" default="100" type="xs:positiveInteger"/>
        <xs:attribute name="coreCount" fixed="1" type="xs:positiveInteger"/> <!-- TODO: fixed for now, change when multicore -->
    </xs:complexType>
    <xs:complexType name="schedulerConfig">
        <xs:sequence>
            <xs:element name="fullyQualifiedClassName" type="xs:string"/>
            <xs:any minOccurs="0"/> <!-- instance configuration -->
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="quantumDeclaration">
        <xs:restriction base="xs:nonNegativeInteger"/>
    </xs:simpleType>

    <xs:element name="quantum" type="quantumDeclaration"/>
</xs:schema>